### ISSUE TITLE
Backend crashes when accessing swagger/generating swagger schema

### ISSUE THREAD

**Issue by nmdanny** [ScDor/Closure#105]
**Describe the bug**

There's an error that whenever accessing swagger (see below for stack trace)

I'm guessing it might be related to #87

Interestingly, when running locally(via `manage.py`) this doesn't seem too bad, because the server restarts and the user can still authenticate and access swagger endpoints with no problem.

But when running with a real webserver, e.g GCP Cloud run, the effect is more disruptive(it takes longer to restart)

**To Reproduce**

1. Start the server
2. Enter http://localhost:8000/swagger
3. Observe the server's stderr

**Expected behavior**

There should be no internal backend errors when entering the swagger site

**Additional context**

Stack trace:

```
[27/Jun/2021 20:16:57] "GET /swagger/ HTTP/1.1" 200 2223
[27/Jun/2021 20:16:57] "GET /swagger/ HTTP/1.1" 200 2223
[27/Jun/2021 20:16:57] "GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
[27/Jun/2021 20:16:58] "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
[27/Jun/2021 20:16:58] "GET /static/drf-yasg/url-polyfill.min.js HTTP/1.1" 304 0
[27/Jun/2021 20:16:58] "GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
[27/Jun/2021 20:16:58] "GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 304 0
[27/Jun/2021 20:16:58] "GET /static/drf-yasg/immutable.min.js HTTP/1.1" 304 0
[27/Jun/2021 20:16:58] "GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
view's StudentMeViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
  File "E:\Closure\venv\lib\site-packages\django\contrib\auth\models.py", line 420, in __int__
    raise TypeError('Cannot cast AnonymousUser to int. Are you trying to use it in place of User?')
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "E:\Closure\Closure_Project\rest_api\views.py", line 64, in get_queryset
    return Student.objects.filter(user=self.request.user)
  File "E:\Closure\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000027EA96F3490>.
view's MyTrackCourses raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
  File "E:\Closure\venv\lib\site-packages\django\contrib\auth\models.py", line 420, in __int__
    raise TypeError('Cannot cast AnonymousUser to int. Are you trying to use it in place of User?')
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "E:\Closure\Closure_Project\rest_api\views.py", line 33, in get_queryset
    student = Student.objects.get(user=user)
  File "E:\Closure\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000027EA96F3490>.
view's MyTrackCourses raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
  File "E:\Closure\venv\lib\site-packages\django\contrib\auth\models.py", line 420, in __int__
    raise TypeError('Cannot cast AnonymousUser to int. Are you trying to use it in place of User?')
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "E:\Closure\Closure_Project\rest_api\views.py", line 33, in get_queryset
    student = Student.objects.get(user=user)
  File "E:\Closure\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000027EA96F3490>.
view's StudentMeViewSet raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
  File "E:\Closure\venv\lib\site-packages\django\contrib\auth\models.py", line 420, in __int__
    raise TypeError('Cannot cast AnonymousUser to int. Are you trying to use it in place of User?')
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "E:\Closure\Closure_Project\rest_api\views.py", line 64, in get_queryset
    return Student.objects.filter(user=self.request.user)
  File "E:\Closure\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000027EA96F3490>.
view's MyTrackCourses raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
  File "E:\Closure\venv\lib\site-packages\django\contrib\auth\models.py", line 420, in __int__
    raise TypeError('Cannot cast AnonymousUser to int. Are you trying to use it in place of User?')
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "E:\Closure\Closure_Project\rest_api\views.py", line 33, in get_queryset
    student = Student.objects.get(user=user)
  File "E:\Closure\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000027EA96F3490>.
view's MyTrackCourses raised exception during schema generation; use `getattr(self, 'swagger_fake_view', False)` to detect and short-circuit this
Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
  File "E:\Closure\venv\lib\site-packages\django\contrib\auth\models.py", line 420, in __int__
    raise TypeError('Cannot cast AnonymousUser to int. Are you trying to use it in place of User?')
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Closure\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 42, in call_view_method
    return view_method()
  File "E:\Closure\Closure_Project\rest_api\views.py", line 33, in get_queryset
    student = Student.objects.get(user=user)
  File "E:\Closure\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Closure\venv\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\Closure\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000027EA96F3490>.
[27/Jun/2021 20:16:59] "GET /swagger/?format=openapi HTTP/1.1" 200 16353
```

**Comment by ilanerukh** [comment]
Looks like it is fixed with filtering with user.id instead of the user.
Will pull request this fix today.

**Comment by ilanerukh** [comment]
fixed in https://github.com/ScDor/Closure/pull/102
