### ISSUE TITLE
crash during Parser/MoonDownloader.py run

### ISSUE THREAD

**Issue by nitsanWojakovsky** [ScDor/Closure#39]
i run the python file, and it crashed with the following error: (fyi - Im using a macOs machine) 
tracks_html wasnt created:
```
96913
multiprocessing.pool.RemoteTraceback:

Traceback (most recent call last):
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1245, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1291, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1240, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 1008, in _send_output
    self.send(msg)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/http/client.py", line 948, in send
    self.connect()
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1036a7be0>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='moon.cc.huji.ac.il', port=80): Max retries exceeded with url: /nano/pages/wfrCourse.aspx?faculty=2&year=2021&courseId=7412 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036a7be0>: Failed to establish a new connection: [Errno 60] Operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/Closure_Project/Parser/MoonDownloader.py", line 15, in download_course
    f.write(requests.get(url).content)
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/nitsan.wojakovsky/Desktop/university/openSource/Closure/venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='moon.cc.huji.ac.il', port=80): Max retries exceeded with url: /nano/pages/wfrCourse.aspx?faculty=2&year=2021&courseId=7412 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1036a7be0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Parser/MoonDownloader.py", line 64, in <module>
    download_all()
  File "Parser/MoonDownloader.py", line 59, in download_all
    download_all_courses()
  File "Parser/MoonDownloader.py", line 46, in download_all_courses
    pool.map(download_course, (i for i in range(1_000, 100_000)))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /nano/pages/wfrCourse.aspx?faculty=2&year=2021&courseId=7412 (Caused by None)```

**Comment by ScDor** [comment]
Hi Nitzan, thanks for opening the issue

Seems like the website was not responding. Currently, we have this "primitive" retry mechanism. 
@yaelmualem was talking about implementing a `retry` mechanism in the `requests.get` part, that would probably solve such issues. 

Try running it again, or just load the parsed data (sent you privately) instead, until this is fixed

**Comment by ScDor** [comment]
most likely solved in the aforementioned issue. If you encounter this issue again, please comment/reopen this issue.
